version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: ⬆
    reviewers:
      - "pawahtun"
    assignees:
      - "pawahtun"
    labels:
      - "github-actions"
    # Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "America/Mexico_City"
    commit-message:
      prefix: ⬆
    reviewers:
      - "pawahtun"
    assignees:
      - "pawahtun"      
    labels:
      - "pip"
      - "dependencies"